-- STUB / PRODUCTION:
-- This file is intentionally left without executable SQL.
-- Reason: it was a TEMPLATE with placeholders ([...]) and it broke autoloading.
-- Real template: ../templates/transition_tbc_to_wotlk_vendors.sql.template
